version: "3.8"

services:

    postgresSQL:
      container_name: company-db
      image: postgres:13.2-alpine
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres